pasteme/pasteme/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [    
    path('', include('userzone.urls')),
    path('admin/', admin.site.urls),
    path('userzone/', include('userzone.urls')),
    path('accounts/', include('accounts.urls')),
]

pasteme/userzone/urls.py
from django.urls import path, re_path
from django.conf.urls import handler404, handler500

from . import views

urlpatterns = [
    # path('', views.list_paste_template, name = 'list_paste_template'),
    path('', views.index, name = 'index_page'),
    path('list_paste', views.list_paste_template, name = 'list_paste_template'),
    path('create_paste', views.create_paste_template, name = 'create_paste_template'),    
    path('update_paste/<int:id>', views.update_paste_template, name = 'update_paste_template'),
    path('delete_paste/<int:id>', views.delete_paste_template, name = 'delete_paste_template'),
    path('review_paste/<slug:id>', views.review_paste_template, name = 'review_paste_template'),
    path('go_to_paste/', views.go_to_paste_template, name = 'go_to_paste_template'),
    path('search_paste/', views.search_paste_template, name = 'search_paste_template'),
    path('create_paste_guest/', views.create_paste_guest_template, name = 'create_paste_guest_template'),
    path('create_tool_guest/', views.create_paste_tool_guest_template, name = 'create_paste_tool_guest_template'),
    path('review_paste_guest/<slug:id>', views.review_paste_guest_template, name = 'review_paste_guest_template'),
    path('go_to_paste_guest/', views.go_to_paste_guest_template, name = 'go_to_paste_guest_template'),    
    path('upload/', views.simple_upload, name = 'simple_upload'),
    path('read/', views.read_content_file, name = 'read_content_file'),
    
    
]

pasteme/userzone/models.py
from django.db import models
from django.utils import timezone
from django.utils.crypto import get_random_string

# Create your models here.


class Paste(models.Model):

    paste_name = models.CharField(max_length=200)
    type_content_paste = models.CharField(max_length=200)
    content_paste = models.TextField()
    time_create = models.DateTimeField(auto_now_add=True)
    time_end = models.DateTimeField(auto_now=True)
    is_private = models.BooleanField(default=0)
    short_link = models.SlugField(max_length=255, unique=True)
    user_own = models.CharField(max_length=200)
    class Meta:
        ordering = ['-time_create']
    def __str__(self):
        return self.paste_name

    def save(self, *args, **kwargs):
        if not self.short_link:
            self.short_link = get_random_string(length=10)
        super().save()

pasteme/userzone/forms.py
from django import forms
from .models import Paste


# class NameForm(forms.Form):
#     your_name = forms.CharField(label='Your name', max_length=100)


# class PasteForm(forms.ModelForm):    
#     class Meta:
#         model = Paste
#         fields = ['paste_name', 'type_content_paste','content_paste', 'user_own', 'short_link']

class PasteCreateForm(forms.ModelForm):
    class Meta:
        model = Paste
        fields = ['paste_name', 'type_content_paste','content_paste',]       
        widgets = {
            'paste_name': forms.fields.TextInput(attrs={               
                'class': 'form-control',
            }),
            'type_content_paste': forms.Select(                
                attrs={               
                    'class': 'form-control',
                }
            ),
            'content_paste': forms.Textarea(attrs={               
                'class': 'form-control'
            }),            
        }

class PasteFileForm(forms.ModelForm):
    class Meta:
        model = Paste
        fields = ['paste_name', 'type_content_paste',]       
        widgets = {
            'paste_name': forms.fields.TextInput(attrs={               
                'class': 'form-control',
            }),
            'type_content_paste': forms.Select(                
                attrs={               
                    'class': 'form-control',
                }
            ),            
        }
        

pasteme/userzone/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import loader
from django.views import generic
from .models import Paste
from .forms import PasteCreateForm,PasteFileForm
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import os
from django.conf import settings
from .helper import FileIO
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse


# Create your views here.

NUMBER_ITEM_PER_PAGE = 5
SUPPORT_LANGUAGE = ['Apache', 'Bash', 'C#', 'C++', 'CSS', 'CoffeeScript', 'Diff', 'HTML', 'XML', 'HTTP', 'Ini',  
                    'JSON', 'Java', 'JavaScript', 'Makefile', 'Markdown', 'Nginx', 'Objective-C', 'PHP', 'Perl',  
                    'Python', 'Ruby', 'SQL', 'Shell Session'] 

def index(request):
    if request.user.is_authenticated:
        return redirect('list_paste_template')
    return redirect('create_paste_guest_template')


@login_required
def list_paste_template(request):
    Pastes = Paste.objects.filter(user_own=request.user.username)
    paginator = Paginator(Pastes, NUMBER_ITEM_PER_PAGE)
    page = request.GET.get('page')
    Pastes_with_paginator = paginator.get_page(page)
    return render(request, 'userzone/paste_lists.html',{'Pastes':Pastes_with_paginator,
                                                        'title':'Lists Paste' ,'sub_title':'All your code'} )
@login_required
def search_paste_template(request):    
    search_text = request.GET.get('id')
    Pastes = Paste.objects.filter(user_own=request.user.username, paste_name__contains=search_text)    
    paginator = Paginator(Pastes, NUMBER_ITEM_PER_PAGE)
    page = request.GET.get('page')
    Pastes_with_paginator = paginator.get_page(page)
    return render(request, 'userzone/paste_lists.html',{'Pastes':Pastes_with_paginator, 'title':'Search Paste',
                                                        'sub_title':'Search your code','search_text':search_text,})
@login_required
def go_to_paste_template(request):    
    short_link = request.GET.get('id')            
    return redirect('review_paste_template', id=short_link)

def go_to_paste_guest_template(request):    
    short_link = request.GET.get('id')    
    #print(short_link)        
    #return redirect('create_paste_guest_template')
    return redirect('review_paste_guest_template', id=short_link)

@login_required
def create_paste_template(request):
    form = PasteFileForm(request.POST or None)
    list_syntax = SUPPORT_LANGUAGE
    if form.is_valid():        
        obj = form.save(commit=False)
        obj.user_own = request.user.username
        obj.save()
        content = request.POST.get('content_paste')
        target = Paste.objects.get(id=obj.id)     
        try:
            FileIO.writeToFile(content, target.short_link)           
        except IOError:
            return redirect('index_page')
        return redirect('review_paste_template', id=target.short_link)

    return render(request, 'userzone/paste_create.html', {'form': form, 'title':'Create Paste', 
                                                        'sub_title':'Lets Sharing your code','list_syntax':list_syntax})

@login_required
def update_paste_template(request,id):
    #Paste_ = Paste.objects.get(id=id)   
    Paste_ = get_object_or_404(Paste, id=id) 
    list_syntax = SUPPORT_LANGUAGE
    form = PasteFileForm(request.POST or None, instance=Paste_)  
    content = ''  
    try:
        content = FileIO.readFile(Paste_.short_link)  
    except IOError:
        return redirect('index_page')    
    if form.is_valid():
        form.save()        
        content = request.POST.get('content_paste')    
        try:
            FileIO.writeToFile(content, target.short_link)           
        except IOError:
            return redirect('index_page')    
        #FileIO.writeToFile(content, Paste_.short_link)

        return redirect('review_paste_template', id=Paste_.short_link)
    return render(request, 'userzone/paste_create.html', {'form': form, 'paste': Paste_, 'title':'Update Paste' ,
                                                        'sub_title':'Changing your code','list_syntax':list_syntax,
                                                        'content_paste':content })

@login_required
def delete_paste_template(request,id):
    Paste_ = get_object_or_404(Paste, id=id)
    #Paste_ = Paste.objects.get(id=id)
    if request.method == 'POST':
        Paste_.delete()
        return redirect('list_paste_template')
    
    return render(request, 'userzone/paste_delete.html', {'paste': Paste_, 'title':'Delete Paste' ,'sub_title':'Remote your code'})

@login_required
def review_paste_template(request,id):
    Paste_ = get_object_or_404(Paste, short_link=id)
    #Paste_ = Paste.objects.get(short_link=id)  
    content = ''
    try:
        content = FileIO.readFile(Paste_.short_link)          
    except IOError:
        return redirect('index_page')  
    return render(request, 'userzone/paste_review.html', {'paste': Paste_, 'title':'Review Paste' ,
                                                        'sub_title':'See your code', 'content_paste':content})

@csrf_exempt
def create_paste_guest_template(request):
    form = PasteFileForm(request.POST or None)
    list_syntax = SUPPORT_LANGUAGE
    if form.is_valid():        
        obj = form.save(commit=False)         
        obj.save()
        target = Paste.objects.get(id=obj.id)        

        content_paste = request.POST.get('content_paste')
        #print(content_paste)
        try:
            FileIO.writeToFile(content_paste, target.short_link)        
        except IOError:
            return redirect('index_page') 

        return redirect('review_paste_guest_template', id=target.short_link)
    return render(request, 'userzone/paste_create_guest.html', {'form': form, 'title':'Create Paste', 
                                                                'sub_title':'Lets Sharing your code','list_syntax':list_syntax})

@csrf_exempt
def create_paste_tool_guest_template(request):
    form = PasteFileForm(request.POST or None)
    list_syntax = SUPPORT_LANGUAGE
    if form.is_valid():        
        obj = form.save(commit=False)         
        obj.save()
        target = Paste.objects.get(id=obj.id)        

        content_paste = request.POST.get('content_paste')
        #print(content_paste)
        FileIO.writeToFile(content_paste, target.short_link)        

        return HttpResponse(target.short_link, status=200)
    return HttpResponse('FAIL TO CREATE PASTE', status=400)

def review_paste_guest_template(request,id):
    Paste_ = get_object_or_404(Paste, short_link=id)
    #Paste_ = Paste.objects.get(short_link=id)    
    content = ''
    try:
        content = FileIO.readFile(Paste_.short_link)       
    except IOError:
        return redirect('index_page')  
    str_content = str(content)
    return render(request, 'userzone/paste_review_guest.html', {'paste': Paste_, 'title':'Review Paste' ,'sub_title':'See your code', 
                                                                'content_paste':content, 'str_content': str_content})

def create_paste_file_guest_template(request):
    form = PasteCreateForm(request.POST or None)
    list_syntax = SUPPORT_LANGUAGE
    if form.is_valid():        
        obj = form.save(commit=False)        
        #obj.save()
        #target = Paste.objects.get(id=obj.id)        
        #return redirect('review_paste_guest_template', id=target.short_link)
    return render(request, 'userzone/paste_create_guest.html', {'form': form, 'title':'Create Paste', 
                                                                'sub_title':'Lets Sharing your code','list_syntax':list_syntax})

def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'userzone/simple_upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'userzone/simple_upload.html')

def read_content_file(request):        
    get_file = os.path.join(settings.MEDIA_ROOT, 'README.md')
    #print(get_file)
    file = open(get_file, "r") 
    content= file.read()
    return render(request, 'userzone/review_upload_file.html',{
        'content':content,
    })

pasteme/userzone/templates/userzone/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  {% load helper_base_template %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Blank Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'userzone/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'userzone/test.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'userzone/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'userzone/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'userzone/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'userzone/dist/css/skins/_all-skins.min.css' %}">
  {% block scrlink %}
  {% endblock %}
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    {% Logo %}
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          {% Notification %}
          <!-- User Account: style can be found in dropdown.less -->
          {% User_Account_Menu request.user %}
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    {% sidebar_content request.user %}
    <!-- /.sidebar -->
  </aside>

  <!-- =============================================== -->

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    {% block headercontent %}
    {% endblock %}
    

    <!-- Main content -->
    {% block maincontent %}
    {% endblock %}
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->
{% block scrscript %}
{% endblock %}
<!-- jQuery 3 -->
<script src="{% static 'userzone/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'userzone/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- SlimScroll -->
<script src="{% static 'userzone/bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'userzone/bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'userzone/dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'userzone/dist/js/demo.js' %}"></script>
<script>
  $(document).ready(function () {
    $('.sidebar-menu').tree()
  })
</script>
</body>
</html>

pasteme/userzone/templates/userzone/paste_create.html
{% extends 'userzone/base.html' %}

{% block headercontent %}
<section class="content-header">
  <h1>
    {{ title }}

    <small>{{ sub_title }}</small>
  </h1>
</section>
{% endblock %}

{% block maincontent %}

<section class="content">

    <div class="box box-warning">
        <div class="box-header with-border">
            <h3 class="box-title">Information</h3>
            
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <form role="form" method="POST">      
                {% csrf_token %}      
                <!-- {{ form.paste_name }} -->
                <div class="form-group">
                    <label>Paste Name</label>
                    {{form.paste_name}}
                </div>
                <div class="form-group">
                    <label>Typepaste</label>
                    <select name="type_content_paste" id="id_type_content_paste" maxlength="200" class="form-control">
                        {% if paste.type_content_paste is none %}
                        <option value="" selected=""></option>
                        {% else %}
                        <option value="{{paste.type_content_paste}}">{{paste.type_content_paste}}</option>
                        {% endif %}
                        {% for item in list_syntax %}
                        <option value="{{item}}" >{{item}}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- <div class="form-group">
                    <label>Short Link</label>
                    {{form.short_link}}
                </div>    -->
                <!-- <div class="form-group">
                    <label>User own</label>
                    {{form.user_own}}
                </div>                 -->
                
                <div class="form-group">
                    <label>Content paste</label>
                    <textarea name="content_paste" required="" cols="40" class="form-control" id="id_content_paste" rows="10">{{content_paste}}</textarea>
                    <!--<textarea class="form-control" rows="10" placeholder="Enter ..."></textarea>-->
                </div>                            

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>                                
            </form>
        </div>
    </div>
</section>

{% endblock %}

pasteme/userzone/templates/userzone/paste_create_guest.html
{% extends 'userzone/base_guest.html' %} 
{% load helper_base_template %}

{% block headercontent %}
<!-- <section class="content-header">
  <h1>
    Create new paste
    <small>Release 1.0</small>
  </h1>
  
</section> -->
{% endblock %} 
{% block maincontent %}
<section class="content">
  <div class="row">
    <div class="col-md-10">
        <div class="box box-warning">
            <div class="box-header with-border">
              <h3 class="box-title">Information</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <form role="form" method="POST">                
                <!-- {{ form.paste_name }} -->
                <div class="form-group">
                  <label>Paste Name</label>
                  {{form.paste_name}}
                </div>
                <div class="form-group">
                  <label>Typepaste</label>
                  <select name="type_content_paste" id="id_type_content_paste" maxlength="200" class="form-control">
                    {% if paste.type_content_paste is none %}
                    <option value="" selected=""></option>
                    {% else %}
                    <option value="{{paste.type_content_paste}}">{{paste.type_content_paste}}</option>
                    {% endif %} 
                    {% for item in list_syntax %}
                    <option value="{{item}}">{{item}}</option>
                    {% endfor %}
                  </select>
                </div>      
                <div class="form-group">
                  <label>Content paste</label>
                  <textarea name="content_paste" required="" cols="40" class="form-control" id="id_content_paste" rows="10"></textarea>
                  <!--<textarea class="form-control" rows="10" placeholder="Enter ..."></textarea>-->
                </div>                
      
                <div class="box-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
    </div>
    <div class="col-md-2" >
        {% Public_Pastes %}
    </div>
  </div>

    <!-- /.box -->
</section>
{% endblock %}

pasteme/userzone/templates/userzone/paste_delete.html
{% extends 'userzone/base.html' %}

{% block headercontent %}
<section class="content-header">
  <h1>
    {{ title }}

    <small>{{ sub_title }}</small>
  </h1>
</section>
{% endblock %}

{% block maincontent %}
<section class="content">
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Accept delete</h3>
    </div>
    
    <form method="POST" role="form">  
        {% csrf_token %}   
        <div class="box-body">  
            <div class="form-group">
                <label>Paste Name</label>
                <input class="form-control" placeholder="{{paste.paste_name}}" disabled="" type="text">
            </div>
            <div class="form-group">
                <label>Paste URL</label>
                <input class="form-control" placeholder="{{paste.short_link}}" disabled="" type="text">
            </div> 
        </div>             
        <div class="box-footer">
            <button type="submit" class="btn btn-danger">Submit</button>
            <a href="{% url 'index_page' %}" class="btn btn-primary">Back</a>
        </div>
    </form>
</div>
</section>
{% endblock %}

pasteme/userzone/templates/userzone/paste_review.html
{% extends 'userzone/base.html' %}
{% load static %}
{% block scrlink %}
<link rel="stylesheet" href="{% static 'userzone/highlight/styles/default.css' %}">
{% endblock %}

{% block scrscript %}
<script src="{% static 'userzone/highlight/highlight.pack.js' %}"></script>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}


{% block headercontent %}
<section class="content-header">
  <h1>
    {{ title }}

    <small>{{ sub_title }}</small>
  </h1>
</section>
{% endblock %}

{% block maincontent %}
<section class="content">
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Review Code</h3>
        <div class="box-tools pull-right">
            <a href={% url 'review_paste_template' paste.short_link %} type="button" class="btn btn-default"><i class="fa fa-eye"></i></a>     
            <a href={% url 'update_paste_template' paste.id %} type="button" class="btn btn-default"><i class="fa fa-edit"></i></a>
            <a href={% url 'delete_paste_template' paste.id %} type="button" class="btn btn-default"><i class="fa fa-remove"></i></a>   
        </div>
    </div>
    
    <form role="form">  
        {% csrf_token %}   
        <div class="box-body">  
            <pre>
                <code class="{{paste.type_content_paste}}">{{ paste.content_paste }}</code>
            </pre> 
        </div>
        <div class="box-footer">
            <a href="{% url 'list_paste_template' %}" class="btn btn-primary">Back</a>           
        </div>                     
    </form>
</div>
</section>
{% endblock %}